compile:
  stage: build
  artifacts:
    name: "Compiled stuff"
    public: false
    paths:
      - target/
  script:
    - $MAVEN_HOME/bin/mvn clean
    - mvn compile

test:
  stage: test
  needs: [compile]
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-ic.doc.QueryProcessorTest.xml
    reports:
      junit:  target/surefire-reports/TEST-ic.doc.QueryProcessorTest.xml
  script:
    - mvn test

cloud_vm_deploy:
  stage: deploy
  needs:
    - job: test
      artifacts: true
    - job: compile
      artifacts: true
  script:
    - |
      if systemctl --user is-active simplewebapp
        then systemctl --user stop simplewebapp
      fi
      mvn package
      chmod +x target/bin/simplewebapp
      cat simplewebapp.service > ~/.config/systemd/user/simplewebapp.service
      printf "\nExecStart=$PWD/target/bin/simplewebapp" >> ~/.config/systemd/user/simplewebapp.service
      systemctl --user daemon-reload
      systemctl --user start simplewebapp
  environment: staging

heroku_deploy:
  stage: deploy
  needs:
    - job: test
      artifacts: true
    - job: compile
      artifacts: true
  script:
    - dpl --provider=heroku --app=tm1722-tax-exemption-tool --api-key=$heroku_api_key
  environment: production
